services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: waypoint
      POSTGRES_PASSWORD: waypoint_123
      POSTGRES_DB: waypoint_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api_server:
    build: .
    container_name: express_api
    restart: always
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://waypoint:waypoint_123@postgres:5432/waypoint_db?schema=public
    depends_on:
      - postgres

volumes:
  postgres_data:
